# Generated by Django 3.2.5 on 2021-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_shows_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
