# Generated by Django 3.2.5 on 2021-08-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_shows_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='img',
            field=models.URLField(default='https://img.freepik.com/free-vector/tv-show-neon-sign-style-text_44523-738.jpg?size=338&ext=jpg'),
        ),
    ]
