# Generated by Django 3.2.5 on 2021-08-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
